language: python
sudo: false
python:
    - 2.7
    - 3.5
    - 3.6
matrix:
    include:
        - python: "3.7"
          dist: xenial
install:
    - pip install -U pip setuptools
    - pip install -U coverage coveralls
    - pip install -U -e .[tests]
script:
    - coverage run -m zope.testrunner --test-path=src
after_success:
    - coveralls
notifications:
    email: false
cache: pip
